name: Example

on:
  push:
    branches: [ master, Development ]
jobs:
  Make:
    runs-on: ubuntu-latest
    name: Make ${{matrix.work}} ${{matrix.arch}}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: down
        uses: MitchWind/ftp-deploy@master
        with:
            server: ${{ secrets.FTP_SERVER }}
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWOD }}
            server_dir: /
